const recipes=[
 {name:'金汤力',en:'GIN & TONIC',base:'金酒',profile:['清爽','微苦'],time:'3 分钟',sprite:0,intro:'气泡托起杜松子的森林气息，青柠让收尾干净利落。简单，却从不无聊。',ingredients:[['金酒','45 ml'],['汤力水','90 ml'],['青柠','1 角'],['冰块','装满']],steps:['将高球杯冰镇，装满大块冰块。','倒入金酒，沿杯壁缓缓加入冰镇汤力水。','轻轻提拉搅拌一次，以青柠角装饰。'],tip:'汤力水开瓶后立即使用，沿吧勺倒入能保留更多气泡。'},
 {name:'莫吉托',en:'MOJITO',base:'朗姆',profile:['清爽','酸甜'],time:'5 分钟',sprite:1,intro:'薄荷、青柠与气泡交织，像一阵来自哈瓦那的海风，明亮又轻盈。',ingredients:[['白朗姆','45 ml'],['青柠汁','25 ml'],['糖浆','15 ml'],['苏打水','60 ml'],['薄荷','8 片']],steps:['薄荷轻拍醒香，与糖浆、青柠汁放入杯中。','加入白朗姆和碎冰，快速搅拌至杯壁冰凉。','补满苏打水和碎冰，用薄荷枝装饰。'],tip:'不要用力捣碎薄荷，否则叶脉会释放明显苦味。'},
 {name:'黛绮莉',en:'DAIQUIRI',base:'朗姆',profile:['酸甜','干爽'],time:'4 分钟',sprite:2,intro:'朗姆的甘蔗香、鲜榨青柠和恰到好处的甜，构成最纯粹的酸甜平衡。',ingredients:[['白朗姆','60 ml'],['青柠汁','30 ml'],['糖浆','15 ml']],steps:['提前冰镇碟形杯。','将全部配料与冰块放入摇壶。','大力摇和约 12 秒，双重过滤入杯。'],tip:'青柠汁需现榨；若青柠偏酸，可将糖浆增加 5 ml。'},
 {name:'玛格丽特',en:'MARGARITA',base:'龙舌兰',profile:['酸甜','柑橘'],time:'5 分钟',sprite:3,intro:'龙舌兰的植物感撞上橙香与青柠，盐边让每一口都更有层次。',ingredients:[['龙舌兰','50 ml'],['橙味利口酒','25 ml'],['青柠汁','25 ml'],['海盐','半圈盐边']],steps:['用青柠擦湿杯沿外侧，轻压海盐做半圈盐边。','全部液体加冰放入摇壶，大力摇和。','双重过滤入冰镇杯，以青柠片装饰。'],tip:'只给杯沿外侧蘸盐，避免盐落入酒中破坏平衡。'},
 {name:'威士忌酸',en:'WHISKEY SOUR',base:'威士忌',profile:['酸甜','醇厚'],time:'6 分钟',sprite:4,intro:'波本的香草与橡木，被柠檬照亮；柔滑泡沫让口感圆润如绒。',ingredients:[['波本威士忌','60 ml'],['柠檬汁','30 ml'],['糖浆','20 ml'],['蛋清（可选）','20 ml']],steps:['全部配料不加冰，干摇约 10 秒打出泡沫。','加入冰块，再次大力摇和至冰冷。','过滤入装有大冰块的矮杯，点缀柠檬皮。'],tip:'不使用生蛋清时，可用 20 ml 鹰嘴豆水替代。'},
 {name:'古典',en:'OLD FASHIONED',base:'威士忌',profile:['醇厚','微甜'],time:'4 分钟',sprite:5,intro:'波本、糖与苦精的极简组合。橙油掠过酒面，慢慢喝，风味会随冰融化展开。',ingredients:[['波本威士忌','60 ml'],['糖浆','7.5 ml'],['芳香苦精','2 dash'],['橙皮','1 片']],steps:['在调酒杯中加入威士忌、糖浆、苦精与冰。','搅拌约 20 秒，过滤至放有大冰块的矮杯。','挤压橙皮喷香，擦杯沿后放入杯中。'],tip:'使用一块透明大冰，融化更慢，酒体变化也更从容。'},
 {name:'尼格罗尼',en:'NEGRONI',base:'金酒',profile:['苦甜','草本'],time:'4 分钟',sprite:6,intro:'等份的金酒、苦味酒与甜味美思，草本、柑橘和苦甜精准咬合。',ingredients:[['金酒','30 ml'],['金巴利','30 ml'],['甜味美思','30 ml'],['橙皮','1 片']],steps:['将三种酒倒入加满冰的调酒杯。','平稳搅拌约 20 秒，直到充分冰镇。','过滤至大冰块矮杯，挤压橙皮油装饰。'],tip:'开封的甜味美思要冷藏，最好一个月内喝完。'},
 {name:'曼哈顿',en:'MANHATTAN',base:'威士忌',profile:['浓烈','丝滑'],time:'5 分钟',sprite:7,intro:'黑麦的辛香与味美思的草本甜香相拥，是一杯端正、沉稳的夜晚经典。',ingredients:[['黑麦威士忌','60 ml'],['甜味美思','30 ml'],['芳香苦精','2 dash'],['酒渍樱桃','1 颗']],steps:['提前冰镇鸡尾酒杯。','所有液体配料加冰，平稳搅拌 20 秒。','过滤入冰镇杯，放入酒渍樱桃。'],tip:'搅拌而非摇和，能保持酒体清澈与丝滑质地。'},
 {name:'长岛冰茶',en:'LONG ISLAND ICED TEA',base:'综合',profile:['浓烈','酸甜'],time:'6 分钟',sprite:0,sheet:2,intro:'五种烈酒披上柠檬与可乐的轻松外衣，入口顺滑，后劲却不容小觑。',ingredients:[['金酒','15 ml'],['白朗姆','15 ml'],['伏特加','15 ml'],['龙舌兰','15 ml'],['橙味利口酒','15 ml'],['柠檬汁','25 ml'],['糖浆','15 ml'],['可乐','适量']],steps:['高球杯装满冰，将除可乐外的配料加入摇壶。','加冰快速摇和约 8 秒，过滤入杯。','以可乐补满，轻搅一次并用柠檬角装饰。'],tip:'这杯酒酒精度很高，请精确计量并慢慢饮用。'},
 {name:'宇宙大都会',en:'COSMOPOLITAN',base:'伏特加',profile:['酸甜','果香'],time:'5 分钟',sprite:1,sheet:2,intro:'蔓越莓的艳丽果香、青柠的锐度与橙香相遇，清爽、摩登又利落。',ingredients:[['柑橘伏特加','40 ml'],['橙味利口酒','20 ml'],['蔓越莓汁','30 ml'],['青柠汁','15 ml']],steps:['提前冰镇马天尼杯。','全部配料加冰，大力摇和约 12 秒。','双重过滤入杯，用橙皮喷香装饰。'],tip:'蔓越莓汁不宜过量，以免掩盖酒体。'},
 {name:'莫斯科骡子',en:'MOSCOW MULE',base:'伏特加',profile:['清爽','辛辣'],time:'4 分钟',sprite:2,sheet:2,intro:'冰凉铜杯里，姜汁啤酒的辛辣与青柠的酸爽让伏特加变得格外活泼。',ingredients:[['伏特加','45 ml'],['青柠汁','15 ml'],['姜汁啤酒','90 ml'],['青柠','1 角']],steps:['铜杯或高球杯装满冰块。','加入伏特加与青柠汁，补满姜汁啤酒。','轻轻搅匀，用青柠角和薄荷装饰。'],tip:'选择辛辣度高、气泡充足的姜汁啤酒。'},
 {name:'血腥玛丽',en:'BLOODY MARY',base:'伏特加',profile:['咸鲜','辛辣'],time:'6 分钟',sprite:3,sheet:2,intro:'番茄的咸鲜与香料层层展开，是一杯可以按自己口味自由调节的早午餐经典。',ingredients:[['伏特加','45 ml'],['番茄汁','90 ml'],['柠檬汁','15 ml'],['辣椒汁','2 dash'],['伍斯特酱','2 dash'],['盐与黑胡椒','少许']],steps:['高球杯装冰，依次加入所有配料。','在两个杯子间缓慢来回倾倒 3 次混合。','以芹菜杆和柠檬角装饰。'],tip:'缓慢滚调可以避免番茄汁产生过多泡沫。'},
 {name:'椰林飘香',en:'PIÑA COLADA',base:'朗姆',profile:['甜美','热带'],time:'6 分钟',sprite:4,sheet:2,intro:'椰香、菠萝与朗姆组成浓郁的热带假日，奶油般绵滑，又带着明亮果酸。',ingredients:[['白朗姆','50 ml'],['菠萝汁','75 ml'],['椰浆','30 ml'],['青柠汁','10 ml']],steps:['将所有配料与一杯碎冰加入搅拌机。','搅打至细腻顺滑，倒入飓风杯。','补少量碎冰，用菠萝叶与菠萝角装饰。'],tip:'没有搅拌机时可用摇壶大力摇和，再倒在碎冰上。'},
 {name:'浓缩咖啡马天尼',en:'ESPRESSO MARTINI',base:'伏特加',profile:['浓郁','微甜'],time:'7 分钟',sprite:5,sheet:2,intro:'浓缩咖啡的烘烤香与伏特加、咖啡利口酒融合，顶部泡沫细密如天鹅绒。',ingredients:[['伏特加','45 ml'],['咖啡利口酒','20 ml'],['新鲜浓缩咖啡','30 ml'],['糖浆','5 ml']],steps:['现做浓缩咖啡，稍微放凉。','全部配料加满冰，大力摇和 15 秒。','双重过滤入冰镇杯，以三颗咖啡豆装饰。'],tip:'新鲜咖啡的油脂和充分摇和，是形成漂亮泡沫的关键。'},
 {name:'阿佩罗橙光',en:'APEROL SPRITZ',base:'开胃酒',profile:['微苦','气泡'],time:'3 分钟',sprite:6,sheet:2,intro:'明亮橙色里有轻柔苦味、柑橘和充沛气泡，适合悠闲午后，也适合作为开场。',ingredients:[['普罗塞克起泡酒','90 ml'],['阿佩罗','60 ml'],['苏打水','30 ml'],['橙片','1 片']],steps:['大号葡萄酒杯装满冰。','依次倒入起泡酒、阿佩罗和苏打水。','轻提搅拌一次，以橙片装饰。'],tip:'遵循 3:2:1 比例，并先倒起泡酒以保留气泡。'},
 {name:'龙舌兰日出',en:'TEQUILA SUNRISE',base:'龙舌兰',profile:['果香','甜美'],time:'4 分钟',sprite:7,sheet:2,intro:'橙汁与红石榴糖浆在杯中形成日出渐层，果香甜润，是最醒目的派对酒款之一。',ingredients:[['龙舌兰','45 ml'],['橙汁','90 ml'],['红石榴糖浆','15 ml'],['橙片','1 片']],steps:['高球杯装冰，加入龙舌兰和橙汁并轻搅。','沿杯壁缓缓倒入红石榴糖浆，使其自然下沉。','不要再次搅拌，用橙片装饰后上桌。'],tip:'糖浆最后缓慢加入，静置片刻就能得到清晰渐层。'},
 {name:'蓝色泻湖',en:'BLUE LAGOON',base:'伏特加',profile:['清爽','柑橘'],time:'4 分钟',sprite:0,sheet:3,intro:'电光蓝色里是伏特加、柑橘与柠檬汽水的清爽组合，简单明亮，很适合派对。',ingredients:[['伏特加','45 ml'],['蓝橙力娇酒','20 ml'],['柠檬汁','15 ml'],['柠檬汽水','90 ml']],steps:['高球杯装满冰，加入伏特加、蓝橙力娇酒与柠檬汁。','轻轻搅匀，再以冰镇柠檬汽水补满。','用柠檬轮装饰后立即上桌。'],tip:'汽水最后加入且只轻搅一次，能保留漂亮气泡。'},
 {name:'蓝色夏威夷',en:'BLUE HAWAIIAN',base:'朗姆',profile:['热带','绵滑'],time:'6 分钟',sprite:1,sheet:3,intro:'菠萝与椰香把蓝橙的柑橘气息变成热带海水般的蓝绿色，甜美而顺滑。',ingredients:[['白朗姆','30 ml'],['伏特加','15 ml'],['蓝橙力娇酒','20 ml'],['菠萝汁','60 ml'],['椰浆','30 ml']],steps:['将所有配料与一杯碎冰放入搅拌机。','搅打至细腻顺滑，倒入飓风杯。','补碎冰，以菠萝角装饰。'],tip:'想要更清爽，可将椰浆减到 20 ml，并增加 10 ml 青柠汁。'},
 {name:'游泳池',en:'SWIMMING POOL',base:'伏特加',profile:['奶油','热带'],time:'7 分钟',sprite:2,sheet:3,intro:'奶油椰香、菠萝和一抹蓝色交叠，酒体浓郁，像一杯可以喝的度假泳池。',ingredients:[['伏特加','30 ml'],['白朗姆','30 ml'],['蓝橙力娇酒','15 ml'],['菠萝汁','60 ml'],['椰浆','30 ml'],['淡奶油','15 ml']],steps:['除蓝橙力娇酒外的配料与碎冰搅打均匀。','倒入飓风杯，再沿杯壁缓缓加入蓝橙力娇酒。','轻提一次形成蓝白纹理，用菠萝装饰。'],tip:'蓝橙力娇酒最后加入，能留下更漂亮的泳池渐层。'},
 {name:'电光柠檬水',en:'ELECTRIC LEMONADE',base:'伏特加',profile:['酸甜','气泡'],time:'5 分钟',sprite:3,sheet:3,intro:'亮蓝色、柠檬酸甜与充沛气泡组成轻快的一杯，味道比颜色更清新。',ingredients:[['伏特加','45 ml'],['蓝橙力娇酒','20 ml'],['柠檬汁','25 ml'],['糖浆','10 ml'],['苏打水','60 ml']],steps:['伏特加、蓝橙力娇酒、柠檬汁和糖浆加冰摇和。','过滤入装满冰的高球杯。','以苏打水补满，轻搅并用柠檬轮装饰。'],tip:'先尝一口再决定糖浆量，不同柠檬的酸度差异很大。'},
 {name:'蓝色玛格丽特',en:'BLUE MARGARITA',base:'龙舌兰',profile:['酸甜','柑橘'],time:'5 分钟',sprite:4,sheet:3,intro:'经典玛格丽特换上深蓝色外衣，龙舌兰的植物感依旧清晰，柑橘香更加鲜明。',ingredients:[['龙舌兰','45 ml'],['蓝橙力娇酒','25 ml'],['青柠汁','25 ml'],['海盐','半圈盐边']],steps:['用青柠擦湿杯沿外侧，做半圈盐边。','全部液体加冰，大力摇和约 12 秒。','双重过滤入冰镇杯，以青柠片装饰。'],tip:'蓝橙力娇酒已有甜度，通常不需要额外添加糖浆。'},
 {name:'水天使',en:'AQUA VELVA',base:'综合',profile:['浓烈','清爽'],time:'5 分钟',sprite:5,sheet:3,intro:'金酒与伏特加带来干净力度，蓝橙和柠檬则让它明亮清爽，外表轻盈但酒劲不低。',ingredients:[['金酒','30 ml'],['伏特加','30 ml'],['蓝橙力娇酒','20 ml'],['柠檬汁','15 ml'],['苏打水','60 ml']],steps:['除苏打水外的配料加冰快速摇和。','过滤入装满冰的高球杯。','补满苏打水，轻搅并挤入一片柠檬皮。'],tip:'这杯含两种基酒，建议使用足量冰块并慢慢饮用。'},
 {name:'蓝色摩托车',en:'BLUE MOTORCYCLE',base:'综合',profile:['浓烈','酸甜'],time:'6 分钟',sprite:6,sheet:3,intro:'长岛冰茶的蓝色表亲，多种基酒被酸甜与气泡包裹，是热闹派对里的强劲选择。',ingredients:[['伏特加','15 ml'],['金酒','15 ml'],['白朗姆','15 ml'],['龙舌兰','15 ml'],['蓝橙力娇酒','15 ml'],['柠檬汁','25 ml'],['糖浆','15 ml'],['柠檬汽水','适量']],steps:['除汽水外的材料全部加冰摇和约 8 秒。','过滤入装满冰的高球杯。','以柠檬汽水补满，轻搅一次。'],tip:'酒精度很高，请严格控制用量；一杯已包含四种烈酒。'},
 {name:'蓝色星期一',en:'BLUE MONDAY',base:'伏特加',profile:['浓烈','柑橘'],time:'4 分钟',sprite:7,sheet:3,intro:'短饮、清澈、直接，伏特加的纯净与两重橙香组成冷冽的宝石蓝。',ingredients:[['伏特加','45 ml'],['蓝橙力娇酒','15 ml'],['橙味利口酒','10 ml']],steps:['提前冰镇马天尼杯。','全部配料加冰充分搅拌约 20 秒。','过滤入冰镇杯，用橙皮喷香装饰。'],tip:'采用搅拌而不是摇和，可以保持酒体清澈透亮。'},
 {name:'螺丝刀',en:'SCREWDRIVER',base:'伏特加',profile:['清爽','橙香'],time:'3 分钟',sprite:0,sheet:4,intro:'伏特加与橙汁组成最轻松的家庭经典，果香明亮，简单却十分耐喝。',ingredients:[['伏特加','45 ml'],['橙汁','90 ml']],steps:['高球杯装满冰块。','倒入伏特加，再加入冰镇橙汁。','轻轻搅匀，以橙片装饰。'],tip:'使用带少量果肉的鲜榨橙汁，口感会更饱满。'},
 {name:'自由古巴',en:'CUBA LIBRE',base:'朗姆',profile:['酸甜','焦糖'],time:'3 分钟',sprite:1,sheet:4,intro:'朗姆与可乐的焦糖气息被青柠提亮，是比普通朗姆可乐更完整的一杯。',ingredients:[['白朗姆','50 ml'],['青柠汁','10 ml'],['可乐','120 ml']],steps:['高球杯装满冰，挤入青柠汁。','加入白朗姆，以冰镇可乐补满。','轻搅一次，用青柠角装饰。'],tip:'青柠汁是这杯酒的灵魂，不建议省略。'},
 {name:'威士忌嗨棒',en:'WHISKY HIGHBALL',base:'威士忌',profile:['清爽','麦芽'],time:'4 分钟',sprite:2,sheet:4,intro:'冰、威士忌与苏打水的极简组合，气泡放大麦芽香，也让酒体轻盈修长。',ingredients:[['威士忌','45 ml'],['苏打水','120 ml']],steps:['用冰块充分冰镇高球杯，并滤掉融水。','倒入威士忌搅拌数次，再沿杯壁加入苏打水。','轻提一次混合，以柠檬皮装饰。'],tip:'杯、酒和苏打水都要足够冰，才能保持细密气泡。'},
 {name:'帕洛玛',en:'PALOMA',base:'龙舌兰',profile:['清爽','微苦'],time:'4 分钟',sprite:3,sheet:4,intro:'龙舌兰遇上西柚的酸甜微苦，轻快的气泡让它成为非常适合佐餐的长饮。',ingredients:[['龙舌兰','45 ml'],['青柠汁','15 ml'],['西柚汽水','100 ml']],steps:['可选：为高球杯做半圈盐边，再装满冰。','加入龙舌兰与青柠汁，补满西柚汽水。','轻轻搅匀，以西柚角装饰。'],tip:'买不到西柚汽水时，可用西柚汁 60 ml 加苏打水 40 ml。'},
 {name:'海风',en:'SEA BREEZE',base:'伏特加',profile:['酸甜','莓果'],time:'3 分钟',sprite:0,sheet:5,intro:'蔓越莓的酸甜与西柚的轻苦交织，伏特加让整体保持干净清爽。',ingredients:[['伏特加','40 ml'],['蔓越莓汁','60 ml'],['西柚汁','60 ml']],steps:['高球杯装满冰块。','依次倒入伏特加、蔓越莓汁和西柚汁。','轻轻搅匀，以西柚片或青柠角装饰。'],tip:'选择无额外加糖的果汁，可以避免成品过甜。'},
 {name:'黑暗风暴',en:"DARK 'N' STORMY",base:'朗姆',profile:['辛辣','焦糖'],time:'4 分钟',sprite:1,sheet:5,intro:'辛辣姜汁啤酒托起深色朗姆的糖蜜香，深浅分层如暴风云压过海面。',ingredients:[['深色朗姆','50 ml'],['姜汁啤酒','100 ml'],['青柠汁','15 ml']],steps:['高球杯装冰，加入青柠汁和姜汁啤酒。','将深色朗姆沿吧勺缓缓浮在顶部。','以青柠角装饰，饮用前轻搅。'],tip:'想保留漂亮分层，就把朗姆放在最后缓慢加入。'},
 {name:'金菲士',en:'GIN FIZZ',base:'金酒',profile:['酸甜','气泡'],time:'5 分钟',sprite:2,sheet:5,intro:'柠檬酸香、细腻泡沫和苏打气泡让金酒变得明亮轻盈，是经典家庭酸酒。',ingredients:[['金酒','45 ml'],['柠檬汁','30 ml'],['糖浆','15 ml'],['苏打水','60 ml']],steps:['将金酒、柠檬汁和糖浆加冰大力摇和。','过滤入不加冰的高球杯。','缓慢补入苏打水，以柠檬片装饰。'],tip:'充分摇和能带来轻薄泡沫；苏打水一定最后加入。'},
 {name:'白俄罗斯',en:'WHITE RUSSIAN',base:'伏特加',profile:['奶油','咖啡'],time:'4 分钟',sprite:3,sheet:5,intro:'咖啡利口酒的烘烤甜香与奶油相融，是一杯圆润浓郁的液体甜点。',ingredients:[['伏特加','40 ml'],['咖啡利口酒','20 ml'],['淡奶油','30 ml']],steps:['矮杯装入大块冰，加入伏特加和咖啡利口酒。','轻轻搅匀。','将淡奶油沿吧勺缓慢浮在表面。'],tip:'饮用前可轻搅形成大理石纹，也可保留分层逐口变化。'},
 {name:'黑俄罗斯',en:'BLACK RUSSIAN',base:'伏特加',profile:['浓郁','微甜'],time:'3 分钟',sprite:0,sheet:6,intro:'只有伏特加与咖啡利口酒，结构直接、酒体强劲，带着深沉的烘烤甜香。',ingredients:[['伏特加','50 ml'],['咖啡利口酒','25 ml']],steps:['矮杯装入一块大冰。','倒入伏特加和咖啡利口酒。','搅拌约 15 秒至充分冰镇。'],tip:'喜欢更干爽时，可把咖啡利口酒减少至 15 ml。'},
 {name:'淘金热',en:'GOLD RUSH',base:'威士忌',profile:['蜂蜜','酸甜'],time:'5 分钟',sprite:1,sheet:6,intro:'波本的香草橡木、柠檬的明亮酸度和蜂蜜的温润甜感，简单而有质感。',ingredients:[['波本威士忌','60 ml'],['柠檬汁','25 ml'],['蜂蜜糖浆','20 ml']],steps:['将蜂蜜与等量温水调成蜂蜜糖浆并放凉。','全部配料加冰大力摇和约 12 秒。','过滤至装有大冰块的矮杯，以柠檬皮装饰。'],tip:'蜂蜜直接加入冷酒很难溶解，先制成糖浆会更均匀。'},
 {name:'含羞草',en:'MIMOSA',base:'起泡酒',profile:['轻盈','果香'],time:'2 分钟',sprite:2,sheet:6,intro:'橙汁与起泡酒等份相遇，果香轻快、酒精感柔和，是最经典的早午餐酒款。',ingredients:[['起泡酒','75 ml'],['橙汁','75 ml']],steps:['提前冰镇香槟杯、起泡酒和橙汁。','先倒入橙汁，再缓慢加入起泡酒。','无需搅拌，直接上桌。'],tip:'所有材料充分冰镇即可，不要加冰以免稀释。'},
 {name:'法式75',en:'FRENCH 75',base:'金酒',profile:['清爽','优雅'],time:'5 分钟',sprite:3,sheet:6,intro:'金酒与柠檬构成清晰骨架，起泡酒让它轻盈华丽，口感优雅但酒劲并不弱。',ingredients:[['金酒','30 ml'],['柠檬汁','15 ml'],['糖浆','10 ml'],['起泡酒','60 ml']],steps:['金酒、柠檬汁和糖浆加冰摇和约 10 秒。','过滤入冰镇香槟杯。','缓慢补入起泡酒，以柠檬长皮装饰。'],tip:'起泡酒最后加入，不要再次大力搅拌。'}
];
const $=s=>document.querySelector(s),grid=$('#recipeGrid');let current=null,favorites=new Set(JSON.parse(localStorage.getItem('cupAtlasFavorites')||'[]')),filter='全部',onlyFavorites=false;
const spriteStyle=r=>{const cols=r.sheet>=4?2:4,x=r.sprite%cols,y=Math.floor(r.sprite/cols),file=r.sheet?`cocktails-grid-${r.sheet}.png`:'cocktails-grid.png';return`--x:${x};--y:${y};--img:url('assets/${file}');--sprite-size:${cols*100}% 200%;--sprite-position:${x*100/(cols-1)}% ${y*100}%`};
function renderFilters(){const labels=['全部','金酒','朗姆','伏特加','威士忌','龙舌兰','其他'];$('#filters').innerHTML=labels.map(x=>`<button class="${x===filter?'active':''}" data-filter="${x}">${x}</button>`).join('')}
function render(){const q=$('#search').value.trim().toLowerCase();const core=['金酒','朗姆','伏特加','威士忌','龙舌兰'];const list=recipes.filter(r=>(filter==='全部'||r.base===filter||(filter==='其他'&&!core.includes(r.base)))&&(!onlyFavorites||favorites.has(r.name))&&(!q||[r.name,r.en,r.base,...r.profile,...r.ingredients.flat()].join(' ').toLowerCase().includes(q)));$('#resultCount').textContent=`${list.length} 款酒`;grid.innerHTML=list.map(r=>`<article class="recipe-card" tabindex="0" data-name="${r.name}"><div class="card-photo sprite" style="${spriteStyle(r)}"><span class="number">${String(recipes.indexOf(r)+1).padStart(2,'0')}</span><button class="heart ${favorites.has(r.name)?'saved':''}" data-save="${r.name}" aria-label="收藏${r.name}">${favorites.has(r.name)?'♥':'♡'}</button></div><div class="card-copy"><div class="card-title"><div><h3>${r.name}</h3><p>${r.en}</p></div><span>${r.time}</span></div><p class="intro">${r.intro}</p><div class="meta"><span>${r.base}</span>${r.profile.map(x=>`<span>${x}</span>`).join('')}<b>查看配方 →</b></div></div></article>`).join('');$('#empty').hidden=!!list.length}
function save(name){favorites.has(name)?favorites.delete(name):favorites.add(name);localStorage.setItem('cupAtlasFavorites',JSON.stringify([...favorites]));render();if(current?.name===name)updateSaveButton()}
function openDetail(name){current=recipes.find(r=>r.name===name);if(!current)return;$('#detailPhoto').setAttribute('style',spriteStyle(current));$('#detailIndex').textContent=`${String(recipes.indexOf(current)+1).padStart(2,'0')} / ${recipes.length}`;$('#detailName').textContent=current.name;$('#detailEn').textContent=current.en;$('#detailTags').innerHTML=[current.base,...current.profile,current.time].map(x=>`<span>${x}</span>`).join('');$('#detailIntro').textContent=current.intro;$('#ingredients').innerHTML=current.ingredients.map(([x,n])=>`<li><span>${x}</span><b>${n}</b></li>`).join('');$('#method').textContent=current.steps.length+' 个步骤';$('#steps').innerHTML=current.steps.map(x=>`<li><p>${x}</p></li>`).join('');$('#tip').textContent=current.tip;updateSaveButton();$('#detail').showModal();document.body.classList.add('modal-open')}
function updateSaveButton(){const yes=favorites.has(current.name);$('#detailFavorite').textContent=yes?'♥ 已收藏':'♡ 收藏这份配方';$('#detailFavorite').classList.toggle('saved',yes)}
renderFilters();render();
$('#filters').onclick=e=>{const b=e.target.closest('button');if(!b)return;filter=b.dataset.filter;renderFilters();render()};$('#search').oninput=render;grid.onclick=e=>{const saveBtn=e.target.closest('[data-save]');if(saveBtn){e.stopPropagation();save(saveBtn.dataset.save);return}const card=e.target.closest('.recipe-card');if(card)openDetail(card.dataset.name)};grid.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.recipe-card'))openDetail(e.target.dataset.name)};
$('#favoriteToggle').onclick=()=>{onlyFavorites=!onlyFavorites;$('#favoriteToggle').classList.toggle('active',onlyFavorites);$('#favoriteToggle').setAttribute('aria-pressed',onlyFavorites);render()};$('.close').onclick=()=>$('#detail').close();$('#detail').addEventListener('close',()=>document.body.classList.remove('modal-open'));$('#detail').onclick=e=>{if(e.target===$('#detail'))$('#detail').close()};$('#detailFavorite').onclick=()=>save(current.name);$('#randomBtn').onclick=()=>openDetail(recipes[Math.floor(Math.random()*recipes.length)].name);if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js');
