const pantry=new Set(JSON.parse(localStorage.getItem('cupAtlasPantry')||'[]'));
let customRecipes=JSON.parse(localStorage.getItem('cupAtlasCustom')||'[]'),editingCustom=null;
const basic=new Set(['冰块','橙皮','青柠','青柠角','柠檬皮','柠檬角','橙片','薄荷','薄荷叶','海盐','盐与黑胡椒','酒渍樱桃','芹菜杆','菠萝叶']);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const clean=v=>v.trim().replace(/（.*?）|\(.*?\)/g,'').replace(/角|片|枝|颗$/,'');
const available=(need,stock)=>{const n=clean(need);return basic.has(need)||basic.has(n)||stock.some(x=>{const s=clean(x);return s===n||s.includes(n)||n.includes(s)})};
const savePantry=()=>localStorage.setItem('cupAtlasPantry',JSON.stringify([...pantry]));
function addPantryValues(value){value.split(/[，,、;；\n]+/).map(clean).filter(Boolean).forEach(x=>pantry.add(x));savePantry();renderPantry()}
function renderPantry(){const items=[...pantry];$('#pantryTotal').textContent=`${items.length} 种材料`;$('#pantryChips').innerHTML=items.length?items.map(x=>`<button class="pantry-chip" data-remove="${esc(x)}">${esc(x)}<span>×</span></button>`).join(''):'<span class="field-help">尚未添加材料</span>';const common=['金酒','白朗姆','伏特加','龙舌兰','波本威士忌','甜味美思','橙味利口酒','青柠汁','柠檬汁','糖浆','汤力水','苏打水','姜汁啤酒','橙汁','可乐'];$('#quickIngredients').innerHTML=common.filter(x=>!pantry.has(x)).map(x=>`<button data-quick="${x}">＋ ${x}</button>`).join('');renderMatches()}
function neededFor(r){return r.ingredients.map(x=>x[0]).filter(x=>!basic.has(x)&&!basic.has(clean(x)))}
function renderMatches(){const stock=[...pantry],showNear=$('#showNear').checked;const matches=recipes.map(r=>{const missing=neededFor(r).filter(x=>!available(x,stock));return{r,missing}}).filter(x=>x.missing.length===0||(showNear&&x.missing.length===1));$('#matchGrid').innerHTML=matches.map(({r,missing})=>`<article class="match-card ${missing.length?'near':'ready'}"><span>${esc(r.en)}</span><h4>${esc(r.name)}</h4><p>${esc(r.intro)}</p><b class="status">${missing.length?`还差：${esc(missing[0])}`:'✓ 现有材料可以制作'}</b><button data-open-match="${esc(r.name)}">查看完整配方 →</button></article>`).join('');$('#noMatches').hidden=!!matches.length;if(!stock.length){$('#noMatches').querySelector('b').textContent='酒柜还是空的';$('#noMatches').querySelector('p').textContent='先添加几种材料，我会立即为你匹配。'}else if(!matches.length){$('#noMatches').querySelector('b').textContent='暂时没有匹配';$('#noMatches').querySelector('p').textContent='再添加一些配料，或打开“只差 1 种材料”。'}}
$('#addPantry').onclick=()=>{addPantryValues($('#pantryInput').value);$('#pantryInput').value=''};$('#pantryInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('#addPantry').click()}};$('#pantryChips').onclick=e=>{const b=e.target.closest('[data-remove]');if(b){pantry.delete(b.dataset.remove);savePantry();renderPantry()}};$('#quickIngredients').onclick=e=>{const b=e.target.closest('[data-quick]');if(b)addPantryValues(b.dataset.quick)};$('#showNear').onchange=renderMatches;$('#matchGrid').onclick=e=>{const b=e.target.closest('[data-open-match]');if(b)openDetail(b.dataset.openMatch)};
function saveCustom(){localStorage.setItem('cupAtlasCustom',JSON.stringify(customRecipes))}
function parseLines(value,withAmount=false){return value.split('\n').map(x=>x.trim()).filter(Boolean).map(x=>withAmount?x.split(/[|｜]/).map(y=>y.trim()):x)}
function openEditor(id=null){editingCustom=id;const r=customRecipes.find(x=>x.id===id);$('#editorTitle').textContent=r?'编辑配方':'新建配方';$('#customName').value=r?.name||'';$('#customEn').value=r?.en||'';$('#customTaste').value=r?.taste||'';$('#customIngredients').value=r?.ingredients.map(x=>x.join(' | ')).join('\n')||'';$('#customSteps').value=r?.steps.join('\n')||'';$('#customNote').value=r?.note||'';$('#customEditor').showModal()}
function renderCustom(){$('#customGrid').innerHTML=customRecipes.map(r=>`<article class="custom-card"><span class="custom-en">${esc(r.en||'ORIGINAL RECIPE')}</span><h3>${esc(r.name)}</h3><p class="custom-taste">${esc(r.taste||'私人创作')}</p><section><b>配料</b><ul>${r.ingredients.map(x=>`<li>${esc(x[0])}${x[1]?` · ${esc(x[1])}`:''}</li>`).join('')}</ul></section><section><b>制作步骤</b><ol>${r.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></section>${r.note?`<p>${esc(r.note)}</p>`:''}<div class="custom-actions"><button data-edit-custom="${r.id}">编辑</button><button class="delete-custom" data-delete-custom="${r.id}">删除</button></div></article>`).join('');$('#noCustom').hidden=!!customRecipes.length}
$('#newCustom').onclick=()=>openEditor();$('#emptyNewCustom').onclick=()=>openEditor();$('#closeEditor').onclick=$('#cancelEditor').onclick=()=>$('#customEditor').close();$('#customForm').onsubmit=e=>{e.preventDefault();const item={id:editingCustom||String(Date.now()),name:$('#customName').value.trim(),en:$('#customEn').value.trim(),taste:$('#customTaste').value.trim(),ingredients:parseLines($('#customIngredients').value,true),steps:parseLines($('#customSteps').value),note:$('#customNote').value.trim()};if(editingCustom)customRecipes=customRecipes.map(x=>x.id===editingCustom?item:x);else customRecipes.unshift(item);saveCustom();renderCustom();$('#customEditor').close()};$('#customGrid').onclick=e=>{const edit=e.target.closest('[data-edit-custom]'),del=e.target.closest('[data-delete-custom]');if(edit)openEditor(edit.dataset.editCustom);if(del&&confirm('确定删除这份自创配方吗？')){customRecipes=customRecipes.filter(x=>x.id!==del.dataset.deleteCustom);saveCustom();renderCustom()}};
renderPantry();renderCustom();
